name: "Task Issue"
description: "새로운 작업을 등록합니다."
title: "[Task] "
labels: ["feature"]
assignees: ["{{ github.actor }}"]
body:
  - type: markdown
    attributes:
      value: "### 작업 내용을 자세히 작성해주세요."
  - type: textarea
    id: details
    attributes:
      label: "작업 내용"
      description: "어떤 작업인지 설명해주세요."
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: "우선순위"
      options:
        - "낮음"
        - "보통"
        - "높음"
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: "작업 유형"
      options:
        - "feature"
        - "bugfix"
        - "docs"
        - "refactoring"
    validations:
      required: true
